name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake (light + dark)
        uses: Platane/snk@v3
        with:
          github_user_name: vikee-code
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
